### ISSUE TITLE
says ok, not ok, shame! shame! shame!

### ISSUE THREAD

**Issue by daTokenizer** [leafi/fix-spacechem-os-x#6]
well, I've got the script running from 
../Fix Spacechem.app/Contents/Resources
and it said everything was ok, it was not (details below)
then i tried the GUI from
../Fix Spacechem.app/Contents/MacOS 
which had the exact same results

the current problem is that it starts, and then crushes with no error message (the best kind of bugs).

I can't believe i'll have to use a windows computer again 😫

**Comment by leafi** [comment]
Do you already have Mono 4.2.4 installed (at /Library/Frameworks/Mono.framework/Versions/4.2.4/)? My current suspicion is my building based on that version might have baked in a path, and the machine.config hanging around in there interferes with some of my fixes.

If you don't have Mono 4.2.4 installed exactly, this is probably not it... In that case, get me some *.zicrash files please!

Oh, and in any case, this entire script was only built for the Steam version. I've heard it doesn't work with the DRM-free version, but I have no information as to why. *.zicrash files pls.

(If it is the Mono 4.2.4 problem, opening steamapps/common/spacechem/SpaceChem.app/Contents/Resources/SpaceChem.exe.config in a text editor and removing the lines 3 (beginning `<configSections>`) through to line 13 (`</system.net>`) should fix the conflict.)

But, really... feed me *.zicrash files please! They live in ~/.local/Zachtronics Industries/SpaceChem/crashes or something like that.

**Comment by leafi** [comment]
... This is actually probably issue #5. I built the fix wrong 16 days ago and was testing on a non-clean system.

**Comment by leafi** [comment]
v2.2 fixes this.
